/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DATE_H_RPCGEN
#define _DATE_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


#define DATE_PROG 0x00000001
#define DATE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define BIN_DATE 1
extern  enum clnt_stat bin_date_1(void *, long *, CLIENT *);
extern  bool_t bin_date_1_svc(void *, long *, struct svc_req *);
#define STR_DATE 2
extern  enum clnt_stat str_date_1(long *, char **, CLIENT *);
extern  bool_t str_date_1_svc(long *, char **, struct svc_req *);
extern int date_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define BIN_DATE 1
extern  enum clnt_stat bin_date_1();
extern  bool_t bin_date_1_svc();
#define STR_DATE 2
extern  enum clnt_stat str_date_1();
extern  bool_t str_date_1_svc();
extern int date_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DATE_H_RPCGEN */
